config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # create about_path
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
  has_attached_file :image , 
  :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def home
  end
  def about
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin"  if @pin.nil?
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="panel panel-default">
  <div class="panel-footer">Panel footer</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container"> <!-- keeps nav elements from side -->

    <div class="span4 right">      
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
    </div> 
    
  <!-- Brand and toggle get grouped for better mobile display -->
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "about", about_path %>
        <li><%= mail_to "me@domain.com" do %>
            <span class="glyphicon glyphicon-send"></span> -->
        <li><%= link_to "work", "#build" %>
        <li><%= link_to "contact", "#form" %>
        <% end %>

          
        <% if user_signed_in? %>
          <li><%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_pin_path %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-cog"></span>'), edit_user_registration_path %></li>
          <li><%= link_to raw('<span class="glyphicon glyphicon-eject"></span>'), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <!-- <li><%= link_to "sign in", new_user_session_path %></li> -->
        <% end %>
      </ul>
    </div> <!-- /.navbar-collapse -->

        <div class="brand">
      <div class="logo pull-left">
        <%=link_to image_tag( "Logo@2x.svg", :alt => "eskuhn logo"), root_path %> 
      </div> 
      <h3>Eric S Kuhn</h3>
      <h4>Product | Strategy | Design</h4>
    </div>

  </div><!-- /.container-collapse -->
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Eric S Kuhn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

	<%= render 'layouts/header' %>
	<div class="container rightdude">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>eskuhn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

	<%= render 'layouts/header' %>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		
		<%= yield %>


</body>
</html>

app/views/pages/about.html.erb
<div class="row" id="about">
	<!-- BEGINNING FIRST SECTION -->
		<div class="col-md-8 col-md-offset-2">
		<div class="container text-center circle">
		</div>
		<div class="content">
			<p>I'm a Product Guy living in Southern California with my wife and two dogs. Originally from New York, I moved to California for the sun, the ocean, and oddly enough, computers</p><br> 

			<p>I started my first company - a non-profit - in 2004 and have been fascinated by process of making nothing into something ever since.</p><br>

			<p>I specialize in business strategy, product, and design. I advise, build, and fundraise for small companies. Please reach out if you'd like to
			<%= link_to "work together", "#" %>
		</p>
		</div>
	</div>
</div>
		<!-- END OF FIRST SECTION -->

app/views/pages/home.html.erb
	<!-- BEGINNING FIRST SECTION -->

<div class="row" id="about">
	<div class="container col-md-8 col-md-offset-2">
		<div class="container text-center circle">
		</div>
		<div class="content">
			<p>I'm a Product Guy living in Southern California with my wife and two dogs. I started my first company - a non-profit - in 2004 and have been fascinated by the process of making nothing into something ever since.</p><br>

			<p>I specialize in business strategy, product, and design. I advise, build, and invest in tech-enabled small companies in a variety of industries, especially mobile and health.</p><br> 

			<p>Please reach out if you'd like to
			<%= link_to "work together", "#" %>
		</p>
		</div>
	</div>
</div>
		<!-- END OF FIRST SECTION -->

     <!-- #Data -->
<div class="row" id="data">
	<div class="container-fluid">
		<div class="container dark col-md-8 col-md-offset-2">
			<h1>Data is my life</h1>
			<div class= "subhero">
				<%= image_tag("Graph_and_Pie.svg", :alt => "diabetes data design") %>
			</div>
			<div class="content">
				<p>I’m a Type 1 Diabetic, so every day is a numbers game. Data is everywhere, making it beautiful and actionable is my passion.</p><br>

				<p>I believe technology and data can improve health outcomes for everyone. I know from experience</p>
			</div>
		</div>
	</div>
</div>
     <!-- ends Data -->

<!-- #Build -->
<div class="row" id="build">
	<div class="container-fluid">
		<div class="container text-center col-md-8 col-md-offset-2">
			<h1>I like to Build</h1>
			<div class="subhero">
			</div>
			<div class="content">
				<br>
				<p>I build teams, products (physical and digital), and businesses - I even used to build buildings - and I’ve realized one universal truth:</p><br>

				<blockquote><p>You can’t do anything exceptional without an exceptional team. Start there, and the rest is cake.</p></blockquote><br> 

				<p>That’s a lie, it’s still really hard. But, the likelihood of success is much higher, and the process is a lot more rewarding</p><br>
			</div>
		</div>
	</div>
</div>
     <!-- ends Build -->


     <!-- #form -->
<div class="row" id="form">
	<div class="container-fluid">
		<div class="container col-md-8 col-md-offset-2">
			<h1>Send me a note, let's chat</h1>
 
			<div class="text-center content">
				<%= mail_to "@eskuhn", "eskuhn@gmail.com"%><br>
				<%= link_to "@eskuhn", "http://www.twitter.com/eskuhn", :target => "_blank" %><br>
				<%= link_to "in/eskuhn", "https://www.linkedin.com/in/eskuhn", :target => "_blank"  %><br>
				<%= link_to "eskuhn.vsco", "http://eskuhn.vsco.co/", :target => "_blank"  %>
			</div>
		</div>
	</div>
</div>
     <!-- ends Data -->

app/views/pins/_form.html.erb
<%= form_for @pin, html: { :multipart => true }  do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <% if pin.user == current_user %>
        <div class="actions">
          
          <%= link_to raw('<span class="glyphicon glyphicon-cog"></span>'), edit_pin_path(pin) %>
          <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>  
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= image_tag @pin.image.url :medium %>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<% if @pin.user == current_user %>
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>
<%= link_to 'Back', pins_path %>